<?php
/**
 * @file
 * Code for the CA Adv Video Gallery Admin feature.
 */

include_once('ca_adv_video_gallery.features.inc');

/**
 * Implements hook_menu()
 */
function ca_adv_video_gallery_menu() {
  $items['admin/config/worx_features/gallery'] = array(
    'title' => 'Gallery Configuration',
    'description' => 'Override settings for ca_adv_video_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_video_gallery'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/gallery/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_adv_video_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_video_gallery'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_adv_video_gallery_menu_alter(&$items) {
  $items['gallery']['title'] = variable_get('ca_adv_video_gallery_menu_title', 'Video Gallery');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_adv_video_gallery_panels_pre_render($panel, $renderer) {
  if (isset($panel->content['new-9']) && $panel->content['new-9']->subtype == 'ca_adv_video_gallery-ca_adv_video_gallery_list_1') {
    $panel->title = variable_get('ca_adv_video_gallery_panel_title', 'Video Gallery');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_adv_video_gallery_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_adv_video_gallery_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_list_count', 16));
  }
  elseif ($display_id == 'ca_adv_video_gallery_video_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_video_list_count', 16));
  }
}
