<?php
/**
 * @file
 * Code for the CA Adv Video Gallery Admin feature.
 */

include_once('ca_adv_video_gallery.features.inc');

/**
 * Implements hook_menu()
 */
function ca_adv_video_gallery_menu() {
  $items['admin/config/worx_features/adv_gallery'] = array(
    'title' => 'Adv Video Gallery Configuration',
    'description' => 'Override settings for ca_adv_video_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_video_gallery'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/adv_gallery/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_adv_video_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_adv_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_adv_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_adv_video_gallery'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_adv_video_gallery_menu_alter(&$items) {
  $items['video-gallery']['title'] = variable_get('ca_adv_video_gallery_menu_title', 'Video Gallery');
}

/**
 * Implements hook_panels_pre_render().
 */
function ca_adv_video_gallery_panels_pre_render($panel, $renderer) {
  foreach ($panel->content as $key => $value) {
    if ($value->subtype == 'ca_adv_video_gallery_list-ca_adv_video_gallery_list_1') {
      $panel->title = variable_get('ca_adv_video_gallery_panel_title', 'Video Gallery');
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function ca_adv_video_gallery_views_pre_view(&$view, &$display_id, &$args) {
  if ($display_id == 'ca_adv_video_gallery_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_list_count', 12));
  } elseif ($display_id == 'ca_adv_video_gallery_sub_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_sub_list_count', 3));
  }
  if ($display_id == 'adv_video_list_1') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_video_grid_count', 12));
  } elseif ($display_id == 'adv_video_list_2') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_video_grid_count', 8));
  } elseif ($display_id == 'adv_video_list_3') {
    $view->set_items_per_page(variable_get('ca_adv_video_gallery_video_list_count', 4));
  }
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_adv_video_gallery_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_token_info().
 */
function ca_adv_video_gallery_token_info() {
  
  // Define token value, product_category_hierarchy is the token will be used as [node:adv_video_category_hierarchy]
  $data['tokens']['node']['adv_video_category_hierarchy'] = array(
    'name' => t("Adv Video category hierarchy"),
    'description' => t("Hierachy path of the category"),
  );
  
  // Define token value, product_product_path is the token will be used as [node:adv_video_video_path]
  $data['tokens']['node']['adv_video_video_path'] = array(
    'name' => t("Adv Video video path"),
    'description' => t("The path of the category the product is located at"),
  );
  
  // Return associative array of tokens & token types
  return $data;
}

/**
 * Implements hook_tokens().
 */
function ca_adv_video_gallery_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  // Check if token type is node
  if($type == 'node'){
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Check token is adv_product_category_hierarchy
        case 'adv_video_category_hierarchy':
          $cateparent =  $data['node']->field_ca_adv_videog_p_gallery;
          //print_r($data['node']);
          $search  = array(' w/', '/');
          $replace = array(' ', '-');
          if ($cateparent[LANGUAGE_NONE] != NULL) {
            $x = $cateparent[LANGUAGE_NONE][0]['target_id'];
            while ($x > 0) {
              $node = node_load($x);
              $nodetitlefix = str_replace($search, $replace, $node->title);
              if (isset($replacements[$original])) {
                $replacements[$original] = $nodetitlefix . '/' . $replacements[$original];
              } else {
                $replacements[$original] = $nodetitlefix;
              }
              //print_r('Category Path ' . $replacements[$original]);
              $cateparent =  $node->field_ca_adv_videog_p_gallery;
              //print_r('Category Parent ' . $cateparent);
              if ($cateparent != NULL) {
                $x = $cateparent[LANGUAGE_NONE][0]['target_id'];
              } else {
                break;
              }
            }
          }
          //print_r('Category Path ' . $replacements[$original]);
          break;
        // Check token is adv_product_product_path
        case 'adv_video_video_path':
          $category =  $data['node']->field_ca_video_gallery_parent[LANGUAGE_NONE][0]['target_id'];
          //print_r($data['node']);
          $nodepath = 'node/' . $category;
          $path = drupal_get_path_alias($nodepath);
          //print_r($path);
          $replacements[$original] = $path;
          break;
      }
    }
  }
  return $replacements;
}
